# Generated by Django 6.1.1 on 2026-09-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfood', '0004_category_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.RemoveField(
            model_name='food',
            name='price',
        ),
        migrations.RemoveField(
            model_name='food',
            name='rating',
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
