# Generated by Django 6.1.1 on 2026-09-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfood', '0006_category_food_price_food_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_images/')),
            ],
        ),
    ]
